# Stacker
# A Plugin to Stack Player on the top of another Player
# by DavidCraftDev for SanCraft
# GitHub: https://github.com/SanCraftDev
# Twitter: https://twitter.com/SanCraftDev
# Discord: https://discord.gg/y8DhYhv427
#
# Should the stackmode enabled default on join?
defaultOn: false
#
# Should a message be shown when a player a not stackable?
showMessage: true
#
# Should a message be sent to the player when stackmode or immune is activated or deactivated for him by someone else?
sendMessage: true
#
# Should the last state of player be saved until the next Server restart?
saveState: true
#
# Should a Player be on join default immune?
defaultImmune: false
#
# Language (Available Languages: https://github.com/SanCraftDev/Stacker/tree/master/languages)
languageFile: "en"
#
# Should the plugin automatically update?
autoUpdate: true
#
# Update Channel (Available Channels: Stable & master) - Downloaded from our ci (https://ci.sancraft.dev)
updateChannel: "master"
#
# Should the plugin automatically update the Language File? (This will delete your custom changes)
autoUpdateLanguage: true
