# Stacker
# A Plugin to Stack Player on the top of another Player
# by DavidCraftDev for ZoeyVid
# GitHub: https://github.com/ZoeyVid
# Mastodon: https://social.zoeyvid.de/@ZoeyVid
# Twitter: https://twitter.com/ZoeyVid
#
# Should the stackmode enabled default on join?
defaultOn: false
#
# Should a message be shown when a player a not stackable?
showMessage: true
#
# Should a message be sent to the player when stackmode or immune is activated or deactivated for him by someone else?
sendMessage: true
#
# Should the last state of player be saved until the next Server restart?
saveState: true
#
# Should a Player be on join default immune?
defaultImmune: false
#
# Should the stacked be are Player throwable?
throwable: true
#
# Language (Available Languages: https://github.com/ZoeyVid/Stacker/tree/master/languages)
languageFile: "en"
#
# Should the plugin automatically update?
autoUpdate: false
#
# Update Channel (Available Channels: stable & dev) - Downloaded from our ci (https://ci.zvcdn.de)
updateChannel: "dev"
#
# Should the plugin automatically update the Language File? (This will delete your custom changes)
autoUpdateLanguage: true
