name: Build with Maven

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: corretto

    - name: Read .version file
      id: version
      run: echo "version=$(cat .github/.version)" >> $GITHUB_OUTPUT

    - name: Change config.yml if stable
      if: github.ref == 'refs/heads/stable' && github.event_name != 'pull_request'
      run: sed -i "s|\"dev\"|\"stable\"|g" src/main/resources/config.yml

    - name: Build with Maven
      run: | 
       sed -i "s|\"dev\"|\"stable\"|g" src/main/resources/config.yml
       mvn -B package --file pom.xml
       rm -rf target/original-*.jar

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: |
          target/stacker.jar

    - uses: "marvinpinto/action-automatic-releases@latest"
      if: github.event_name != 'pull_request'
      with:
        prerelease: ${{ github.ref != 'refs/heads/stable' }}
        repo_token: ${{ github.token }}
        title: ${{ steps.version.outputs.version }}
        automatic_release_tag: ${{ steps.version.outputs.version }}
        files: |
          target/stacker.jar
