name: Build with Maven
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: corretto
      - name: Read .version file
        id: version
        run: echo "version=$(cat .github/.version)" >> $GITHUB_OUTPUT
      - name: Change config.yml if stable
        if: github.ref_name == 'stable' && github.event_name != 'pull_request'
        run: |
          sed -i "s|updateChannel:.*|updateChannel: \"stable\"|g" src/main/resources/config.yml
      - name: Change config.yml if dev
        if: github.ref_name == 'dev' && github.event_name != 'pull_request'
        run: |
          sed -i "s|updateChannel:.*|updateChannel: \"dev\"|g" src/main/resources/config.yml
      - name: Change config.yml if stable/dev
        if: github.ref_name == 'stable' || github.ref_name == 'dev'
        run: |
          sed -i "s|autoUpdate:.*|autoUpdate: true|g" src/main/resources/config.yml
      - name: Build with Maven
        run: |
          sed -i "s|0.0.0|"$(cat .github/.version)"|g" pom.xml
          mvn -B package --file pom.xml
          rm -rf target/original-*.jar
      - uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: |
            target/stacker.jar
      - uses: "marvinpinto/action-automatic-releases@latest"
        if: github.ref == 'refs/heads/stable' || github.ref == 'refs/heads/dev'
        with:
          prerelease: ${{ github.ref != 'refs/heads/stable' }}
          repo_token: ${{ github.token }}
          title: v${{ steps.version.outputs.version }}
          automatic_release_tag: v${{ steps.version.outputs.version }}
          files: |
            target/stacker.jar
