# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Read .version file
      id: version
      run: echo "::set-output name=version::$(cat .github/.version)"

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: | 
       sed -i 's/0.0.0/${{ steps.version.outputs.version }}/g' pom.xml
       grep pom.xml -e ${{ steps.version.outputs.version }}
       mvn -B package --file pom.xml
       rm -rf target/original*.jar

    - uses: actions/upload-artifact@v3
      with:
        name: artifacts
        path: target/*.jar
